### ISSUE TITLE
Real time spell check causes cursor to jump back while typing. 

### ISSUE THREAD

**Issue by timothevs** [prowriting/beyondgrammar-quill#1]
With the plugin enabled in the QuillJS editor, spelling errors cause the cursor to jump back to the beginning of the misspelled word. 

I've been able to reproduce this error on Opera 58, Safari 12.0.3 (MacOS), and Chrome (Mac). See clip

https://cl.ly/35de8e0a74c0

**Comment by kdepp** [comment]
@timothevs   Please try out the update from #2 ,  if it's still a problem for you, you can reopen this issue and let us know
